# Site settings
title:       Flat priors
email:       ronkeizer@gmail.com
author:      Ron Keizer
description: "Musings on pharmacometrics & clinical pharmacology, statistics, drug development, software engineering, innovation, and other random topics"
baseurl:     ""
url:         "http://ronkeizer.github.io/"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: true
github_username: ronkeizer
twitter_username: ronpirana
google_plus_id:
linkedin_username: ron-keizer
bitcoin_url:
paypal_url: 
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
sass:
  compressed: true
